org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Template Properties
mod_id=template_mod
mod_name=Template Mod
mod_class=TemplateMod

# Mod Properties
mod_license=MIT
mod_version=0.0.1-ALPHA
mod_group_id=github.jodevnull
mod_authors=jo-devnull
mod_description=

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)

# Dependencies
# modrinth.cloth-config=11.1.136+forge
