org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Template Properties
mod_id=redit
mod_name=REdit
mod_class=REdit

# Mod Properties
mod_license=MIT
mod_version=0.1.1-1.21.1
mod_group_id=github.jodevnull
mod_authors=jo-devnull
mod_description=Edit recipes

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)

# Dependencies
modrinth.emi=1.1.22+1.21.1+neoforge
#modrinth.jei=YAcQ6elZ @runtimeOnly